language: node_js

node_js:
  - 10
  - 9
  - 8

before_install: npm install -g greenkeeper-lockfile@1
before_script:  greenkeeper-lockfile-update
after_script:   greenkeeper-lockfile-upload

script:
  - npm run lint
  - npm run test

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules
